#Include 'Totvs.ch'
#Include 'Protheus.ch'


/*
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Programa ºzTComboBox   ºAutor Caio Almeida           ºData 11/02/2026 º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Desc     ºFuncao para criar uma tela com um item de combobox          º±±
±±º          ºcaso necessario, duplique ou apague esta linha              º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Uso      ºEmpresa de uso                                         º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§
*/
User Function zTComboBox()
    Local oDlg1
    Local aOpcoes   := {'Feliz','Animado','Eufórico','Triste','Pensativo','Proteuzando','Codificando','Vagando na net','Só no Insta', 'O pai tá on'}
    Local cOpcao    := aOpcoes[6] 
    Local oCombo
    Local oButton1

    oDlg1 := TDialog():New(0,0,500,500,'Painel de ComboBox',,,,,CLR_BLACK,CLR_WHITE,,,.T.)
    
    oCombo := TComboBox():New(10,10,{ |u|if(PCount()>0,cOpcao:=u,cOpcao)}, aOpcoes,70,20,oDlg1,,{||MsgStop('Mudou para o item ' + cOpcao)},,,,.T.,,,,,,,,,'cCombo')

    oButton1 := TButton():New(10, 100,"Mostar escolha",oDlg1,{||MsgInfo(cOpcao,'Hoje você esta: ')}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. ) 
    oDlg1:Activate(,,,.T.)

Return
