#include 'Totvs.ch'
#include 'Protheus.ch'

/*
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Programa ºfuncao   ºAutor autor             ºData data º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Desc     ºDescricao da funcao                                    º±±
±±º          ºcaso necessario, duplique ou apague esta linha              º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±º Uso      ºEmpresa de uso                                         º±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§
*/


Function zTpanel()
    Local oDlg1
    Local oPanel
    Local oGet1
    Local cGet1 := Space(20)

    oDlg1 := TDialog():New(0,0,300,300,'Teste de TPanel',,,,,CLR_BLACK,CLR_WHITE,,.T.)
    oPanel := TPanel():New(10,10,"Teste",oDlg1,,.T.,,CLR_YELLOW,CLR_BLUE,100,100)



    oDlg1:Activate(,,,.T.)
Return 
